### ISSUE TITLE
Change the value of ServerTokens?

### ISSUE THREAD

**Issue by HCHCHH** [llaumgui/docker-images#1]
In the [config file](https://github.com/llaumgui/docker-images/blob/master/httpd/2.4/conf.d/security.conf), **ServerTokens** is set to **Prod**, which gives the least infomation.

However, the Httpd [official document](https://httpd.apache.org/docs/current/mod/core.html#servertokens) recommends to set **ServerTokens** to **Full** / **OS**. 
"Setting ServerTokens to less than minimal is not recommended because it makes it more difficult to debug interoperational problems. " 

I wonder if you change the value of this parameter on purpose. Thanks.

**Comment by llaumgui** [comment]
I'm not OK with this part of the documentation.
You can override my personnal configuration with a volume.
